### ISSUE TITLE
Apuntes

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ID3#1]
@steveomatic @FelipeSulser @AlvaroFaure 
Formato csv. PROHIBIDO FLEX

Usar la libería de árboles de git hub

**Comment by steveomatic** [comment]
Hola, se me ha ocurrido una super idea, qué tal paralelizar usando threads para cada subárbol? @FelipeSulser

**Comment by HaritzPuerto** [comment]
propongo usar Hadoop para manejar Big Data

**Comment by FelipeSulser** [comment]
ESO ERA MIO

**Comment by AlvaroFaure** [comment]
¿Por qué no lo hacemos en Haskell? La programación funcional es mejor :+1:

**Comment by HaritzPuerto** [comment]
entonces Scala :smile:

**Comment by AlvaroFaure** [comment]
Sugiero ensamblador.

**Comment by HaritzPuerto** [comment]
@AlvaroFaure eres un hombre de verdad!

**Comment by HaritzPuerto** [comment]
http://stackoverflow.com/questions/24299427/how-do-i-convert-csv-file-to-rdd
