### ISSUE TITLE
Tipo de la tupla a clasificar

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ID3#10]
El algoritmo recibe una tupla y la clasifica. Una tupla es una lista de Object. Tiene la misma estructura que una fila de la tabla con la que se entrena, pero no está en esa tabla, si estuviera en la tabla no haría falta clasificarla porque ya sabríamos cuál sería.

Pregunta:
List< >? que pongo ahí? Un Map también valdría. En el parser hay algo definido para eso? @FelipeSulser

**Comment by FelipeSulser** [comment]
¿De que algoritmo hablas? No entiendo. Si se trata de ID3, lo entrenamos con una tabla y una lista ( la query). Y a partir de ahí podemos preguntarle usando los atributos de la tabla.

En esta implementación todos las clases de atributos son String, no se si eso responde a la pregunta.

**Comment by HaritzPuerto** [comment]
El algoritmo si solo entrena no sirve para nada, debe clasificar. Primero entrena, y depués se le pasa una tupla y la clasifica. Espera a que vuelva a mirar lo que hiciste, tal vez por ahí pueda sacarlo
