### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by steveomatic** [HaritzPuerto/ID3#17]
La hacemos en inglés o en español

@HaritzPuerto @FelipeSulser @AlvaroFaure

**Comment by steveomatic** [comment]
(A lo mejor da puntos por hacerlo en inglés) (preguntamos)

**Comment by AlvaroFaure** [comment]
¿Cómo va a dar puntos extra por hacerlo en un idioma en particular? Además, es TRIVIÑO.
