### ISSUE TITLE
Entropía aparentemente no funciona

### ISSUE THREAD

**Issue by steveomatic** [HaritzPuerto/ID3#19]
@AlvaroFaure 

Creo que hay un problema con el cálculo de la entropía, te adjunto los detalles.

Utilizando el siguiente .csv
--------csv
ISHOMEOWNER,MARITALSTATUS,DEFAULTEDBORROWER,UNIVERSITYSTUDIES
yes,single,no,yes
no,married,no,no
no,single,no,yes
yes,married,no,no
no,divorced,yes,yes
no,married,no,no
yes,divorced,no,yes
no,single,yes,no
no,married,no,yes
no,single,yes,no
-----------/csv

cuando llega a gananciaAtributo (decidiendo por DEFAULTEDBORROWER) los valores devueltos son:
Hola, soy Faure y el atributo: ISHOMEOWNER tiene una ganancia de -20.284921071057518
Hola, soy Faure y el atributo: MARITALSTATUS tiene una ganancia de -6.759692344308859
Hola, soy Faure y el atributo: UNIVERSITYSTUDIES tiene una ganancia de -16.453500838470227

son negativas y fuera de rango. ¿Puedes revisar? He comprobado que los valores distintos de cada columna SÍ los coge bien. Te subo el .csv a la rama coreBeginning para que puedas probarlo.

Saludos

**Comment by AlvaroFaure** [comment]
El fallo era que antes mi método valoresDistintos recorría la columna almacenando en un SET todos los valores de la columna. Como son valores String, tienen equals y por tanto el set lo chequea y no almacena los que ya tiene, así que después de recorrer la columna en el set está el conjunto de valores distintos, que devolvía con return. Al llamar a valoresDistintos recibía el set y creaba una lista a partir de eso para trabajar con ello.

HARITZ CUESTIONÓ que cada vez que llamaba al método crease una lista a partir del conjunto y decía que "necesitaba una lista", así que en lugar de hacer como yo y crearla a partir del conjunto de valores distintos que recibe del método cambió mi SET por una LISTA y devolvió eso, así que cuando el for recorre la columna almacena todos los valores y no los valores distintos, dando cosas loquísimas que explica esas entropías bestiales.
