### ISSUE TITLE
Consejo código

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/ID3#20]
List<String> lista = new ArrayList<String>(conjunto);
no
usad:
	List<String> lista = new ArrayList<>(conjunto);

Netbeans lo recomienda

**Comment by AlvaroFaure** [comment]
Y a mí me da error, igual que he tenido que tipar algunas cosas al ejecutarlas ayer porque con mi Java no se puede. Deja en paz las cosas que están BIEN xD
